name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore ExpressionUtils.sln
      - run: dotnet build ExpressionUtils.sln --configuration Release --no-restore
      - run: dotnet test ExpressionUtilsTest/ExpressionUtilsTest.csproj --configuration Debug --no-build --verbosity normal
      - run: dotnet pack ExpressionUtils/ExpressionUtils.csproj --configuration Release --no-build --output ./artifacts
      - uses: NuGet/login@v1
        id: login
        with:
          user: ${{ vars.NUGET_USER }}
      - run: dotnet nuget push './artifacts/*.nupkg' --api-key '${{ steps.login.outputs.NUGET_API_KEY }}' --source https://api.nuget.org/v3/index.json --skip-duplicate
