name: Test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore ExpressionUtils.sln
      - run: dotnet build ExpressionUtils.sln --configuration Release --no-restore
      - run: dotnet test ExpressionUtilsTest/ExpressionUtilsTest.csproj --configuration Release --no-build --verbosity normal
